// client-vue/src/feature/home/HomePage.vue
<template>
  <div class="ui inverted vertical center aligned segment masthead">
    <div class="ui text container">
      <h1 class="ui inverted header">
        <img
          src="/assets/logo.png"
          class="ui massive image"
          style="margin-bottom: 12px; margin-right: -2px"
        />
        Reactivities
      </h1>
    </div>
    <h2 class="ui inverted header">Welcome to Reactivities</h2>
    <router-link
      :to="{ name: ACTIVITY_DASHBOARD_PAGE_NAME }"
      class="ui huge inverted button"
    >
      Take me to the Activities!
    </router-link>
  </div>
</template>

<script setup lang="ts">
import { ACTIVITY_DASHBOARD_PAGE_NAME } from '../../app/constants/routes';
</script>

<style scoped>
.ui.inverted.vertical.center.aligned.segment.masthead {
  justify-content: center;
  flex-direction: column;
}
</style>

// client-react/src/features/homes/HomePage.tsx
import { observer } from 'mobx-react-lite';
import React from 'react';
import { Link } from 'react-router-dom';
import { Container, Header, Segment, Image, Button } from 'semantic-ui-react';
import { ACTIVITIES_PAGE_ROUTE } from '../../app/constants/routes';
import { useStore } from '../../app/stores/store';
import LoginForm from '../users/LoginForm';
import RegisterForm from '../users/RegisterForm';

export default observer(function HomePage(): JSX.Element {
  const { userStore, modalStore } = useStore();
  return (
    <Segment inverted textAlign='center' vertical className='masthead'>
      <Container text>
        <Header as='h1' inverted>
          <Image
            size='massive'
            src='/assets/logo.png'
            alt='logo'
            style={{ marginBottom: 12 }}
          />
          Reactivities
        </Header>
        {userStore.isLoggedIn ? (
          <>
            <Header as='h2' inverted content='Welcome to Reactivities' />
            <Button as={Link} to={ACTIVITIES_PAGE_ROUTE} size='huge' inverted>
              Go to Activities!
            </Button>
          </>
        ) : (
          <>
            <Button
              onClick={() => modalStore.openModal(<LoginForm />)}
              size='huge'
              inverted
            >
              Login!
            </Button>
            <Button
              onClick={() => modalStore.openModal(<RegisterForm />)}
              size='huge'
              inverted
            >
              Register!
            </Button>
          </>
        )}
      </Container>
    </Segment>
  );
});
