// client-app/src/features/errors/ServerErrorPage.tsx
import React from 'react';
import { observer } from 'mobx-react-lite';
import { Container, Header, Segment } from 'semantic-ui-react';
import { useStore } from '../../app/stores/store';

export default observer(function ServerError() {
  const { commonStore } = useStore();
  return (
    <Container>
      <Header as='h1' content='Server Error' />
      <Header sub as='h5' color='red' content={commonStore.error?.message} />
      {commonStore.error?.details && (
        <Segment>
          <Header as='h4' content='Stack trace' color='teal' />
          <code style={{ marginTop: '10px' }}>{commonStore.error.details}</code>
        </Segment>
      )}
    </Container>
  );
});

// client-vue/src/feature/errors/ServerErrorPage.vue
<template>
  <div class="ui container">
    <h1 class="ui header">Server Error</h1>
    <h5 class="ui red sub header">This is a server error</h5>
    <div class="ui segment">
      <h4 class="ui teal header">Stack trace</h4>
      <code style="margin-top: 10px">
        {{ message }}
      </code>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue';
import { useStore } from '../../app/store';

export default defineComponent({
  setup() {
    const store = useStore();

    const details = computed(() => {
      return store.getters.getError?.details;
    });
    const message = computed(() => {
      return store.getters.getError?.message;
    });

    return {
      details,
      message,
    };
  },
});
</script>
