// client-react/src/features/errors/ValidationErrors.tsx
import React from 'react';
import { Message } from 'semantic-ui-react';

interface ValidationErrorsProps {
  errors: any;
}

export default function ValidationErrors({ errors }: ValidationErrorsProps) {
  return (
    <Message error>
      {errors && (
        <Message.List>
          {errors.map((err: any, i: any) => (
            <Message.Item key={i}>{err}</Message.Item>
          ))}
        </Message.List>
      )}
    </Message>
  );
}

// client-vue/src/feature/errors/ValidationErrors.vue
<template>
  <div class="ui error message">
    <ul class="list">
      <li class="content" v-for="(error, i) in errors" :key="i">
        {{ error }}
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  props: {
    errors: {
      type: Array as () => String[],
      required: true,
    },
  },
});
</script>
