// client-vue/src/feature/errors/NotFoundPage.vue
<template>
  <div class="ui placeholder segment">
    <div class="ui icon header">
      <i class="search icon" />
      Oops - we've looked everywhere and could not find this.
    </div>
    <div class="inline">
      <router-link
        class="ui primary button"
        :to="{ name: ACTIVITY_DASHBOARD_PAGE_ROUTE }"
      >
        Return to activities page</router-link
      >
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { ACTIVITY_DASHBOARD_PAGE_ROUTE } from '../../app/constants/routes';

export default defineComponent({
  setup() {
    return {
      ACTIVITY_DASHBOARD_PAGE_ROUTE,
    };
  },
});
</script>

// client-react/src/features/errors/NotFoundPage.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { Button, Header, Icon, Segment } from 'semantic-ui-react';
import { ACTIVITIES_PAGE_ROUTE } from '../../app/constants/routes';

export default function NotFound() {
  return (
    <Segment placeholder>
      <Header icon>
        <Icon name='search' />
        Oops - we've looked everywhere and could not find this.
      </Header>
      <Segment.Inline>
        <Button as={Link} to={ACTIVITIES_PAGE_ROUTE} primary>
          Return to activities page
        </Button>
      </Segment.Inline>
    </Segment>
  );
}
