// client-app/src/features/activities/form/ActivityForm.tsx
import { observer } from 'mobx-react-lite';
import React, { useState, ChangeEvent, useEffect } from 'react';
import { Link, useHistory, useParams } from 'react-router-dom';
import { Button, Form, Segment } from 'semantic-ui-react';
import LoadingComponent from '../../../app/layout/LoadingComponent';
import { Activity } from '../../../app/models/activity';
import { useStore } from '../../../app/stores/store';
import { v4 as uuid } from 'uuid';
import {
  ACTIVITIES_PAGE_ROUTE,
  getActivityDetailsRoute,
} from '../../../app/constants/routes';

export default observer(function ActivityForm() {
  const history = useHistory();
  const { activityStore } = useStore();
  const {
    createActivity,
    updateActivity,
    isLoading,
    loadActivity,
    isLoadingInitial,
  } = activityStore;
  const { id } = useParams<{ id: string }>();

  const [activity, setActivity] = useState<Activity>({
    id: '',
    title: '',
    category: '',
    description: '',
    date: '',
    city: '',
    venue: '',
  });

  useEffect(() => {
    if (id) {
      loadActivity(id).then((activity: Activity | undefined) => {
        setActivity(activity!);
      });
    }
  }, [id, loadActivity]);

  function handleSubmit() {
    if (activity.id) {
      updateActivity(activity).then(() => {
        history.push(getActivityDetailsRoute(activity.id));
      });
    } else {
      let newActivity = {
        ...activity,
        id: uuid(),
      };
      createActivity(newActivity).then(() => {
        history.push(getActivityDetailsRoute(newActivity.id));
      });
    }
  }

  function handleInputChange(
    event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) {
    const { name, value } = event.target;
    setActivity({ ...activity, [name]: value });
  }

  return id && isLoadingInitial ? (
    <LoadingComponent content='Loading activity' />
  ) : (
    <Segment clearing>
      <Form onSubmit={handleSubmit} autoComplete='off'>
        <Form.Input
          placeholder='Title'
          value={activity.title}
          name='title'
          onChange={handleInputChange}
        />
        <Form.TextArea
          placeholder='Description'
          value={activity.description}
          name='description'
          onChange={handleInputChange}
        />
        <Form.Input
          placeholder='Category'
          value={activity.category}
          name='category'
          onChange={handleInputChange}
        />
        <Form.Input
          type='date'
          placeholder='Date'
          value={activity.date}
          name='date'
          onChange={handleInputChange}
        />
        <Form.Input
          placeholder='City'
          value={activity.city}
          name='city'
          onChange={handleInputChange}
        />
        <Form.Input
          placeholder='Venue'
          value={activity.venue}
          name='venue'
          onChange={handleInputChange}
        />
        <Button
          loading={isLoading}
          floated='right'
          positive
          type='submit'
          content='Submit'
        />
        <Button
          as={Link}
          to={ACTIVITIES_PAGE_ROUTE}
          floated='right'
          type='button'
          content='Cancel'
        />
      </Form>
    </Segment>
  );
});

// client-vue/src/feature/activities/form/ActivityForm.vue
<template>
  <div v-if="!(id && isLoadingInitial)" class="ui clearing segment">
    <form @submit.prevent="submit" autocomplete="off" class="ui form">
      <FormInput placeholder="Title" name="title" v-model="activity.title" />
      <FormInput
        placeholder="Description"
        name="description"
        v-model="activity.description"
      />
      <FormInput
        placeholder="Category"
        name="category"
        v-model="activity.category"
      />
      <FormInput
        placeholder="Date"
        inputType="date"
        name="date"
        v-model="activity.date"
      />
      <FormInput placeholder="City" name="city" v-model="activity.city" />
      <FormInput placeholder="Venue" name="venue" v-model="activity.venue" />
      <button
        type="submit"
        class="ui positive right floated button"
        :class="{ loading: isLoading }"
      >
        Submit
      </button>
      <router-link to="/activities" class="ui right floated button">
        Cancel
      </router-link>
    </form>
  </div>
  <Loading v-else content="Loading activity" />
</template>

<script lang="ts">
import { computed, defineComponent, onMounted, reactive } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { v4 as uuid } from 'uuid';
import Loading from '../../../app/components/Loading.vue';
import FormInput from '../../../app/components/FormInput.vue';
import { Activity } from '../../../app/models/activity';
import { useStore } from '../../../app/store';
import { AllActionTypes } from '../../../app/store/action-types';

export default defineComponent({
  components: {
    Loading,
    FormInput,
  },
  setup() {
    const route = useRoute();
    const router = useRouter();
    const store = useStore();
    const { id } = route.params;
    const isLoadingInitial = computed<boolean>(
      () => store.getters.getIsLoadingInitial
    );
    const isLoading = computed<boolean>(() => store.getters.getIsLoading);
    let activity = reactive<Activity>({
      id: '',
      title: '',
      category: '',
      description: '',
      date: '',
      city: '',
      venue: '',
    });

    const submit = () => {
      console.log(activity.title);
      if (activity.id) {
        store.dispatch(AllActionTypes.UPDATE_ACTIVITY, activity).then(() => {
          router.push({ name: 'ActivityDetails', params: { id: activity.id } });
        });
      } else {
        let newActivity = {
          ...activity,
          id: uuid(),
        };
        store.dispatch(AllActionTypes.CREATE_ACTIVITY, newActivity).then(() => {
          router.push({
            name: 'ActivityDetails',
            params: { id: newActivity.id },
          });
        });
      }
    };

    onMounted(() => {
      if (id) {
        store
          .dispatch(AllActionTypes.LOAD_ACTIVITY, id.toString())
          .then((a) => {
            if (a) {
              activity.title = a.title;
              activity.id = a.id;
              activity.description = a.description;
              activity.category = a.category;
              activity.date = a.date;
              activity.city = a.city;
              activity.venue = a.venue;
            }
          });
      }
    });

    const handleChange = (value1: { value: string; name: string }): void => {
      const { value, name } = value1;
      console.log({ value, name });
      (activity as any)[name] = value;
    };

    return {
      activity,
      isLoading,
      isLoadingInitial,
      id,
      submit,
      handleChange,
    };
  },
});
</script>
