// client-vue/src/feature/activities/dashboard/ActivityFilters.vue
<template>
  <div class="ui large vertical menu">
    <div class="ui teal attached header">
      <i class="filter icon" />
      <div class="content">Filters</div>
    </div>
    <div class="item">All Activities</div>
    <div class="item">I'm going</div>
    <div class="item">I'm hosting</div>
  </div>
  <div class="ui header"></div>
  <Calendar />
</template>

<script>
import { defineComponent } from 'vue';
import { Calendar } from 'v-calendar';

export default defineComponent({
  components: {
    Calendar,
  },
});
</script>

// client-app/src/features/activities/dashboard/ActivityFilters.tsx
import React from 'react';
import { Header, Menu } from 'semantic-ui-react';
import Calendar from 'react-calendar';

export default function ActivityFilters() {
  return (
    <>
      <Menu vertical size='large' style={{ width: '100%', marginTop: 25 }}>
        <Header icon='filter' attached color='teal' content='Filters' />
        <Menu.Item content='All Activities' />
        <Menu.Item content="I'm going" />
        <Menu.Item content="I'm hosting" />
      </Menu>
      <Header />
      <Calendar />
    </>
  );
}
