// client-app/src/app/layout/LoadingComponent.tsx
import React from 'react';
import { Dimmer, Loader } from 'semantic-ui-react';

interface LoadingComponentProps {
  inverted?: boolean;
  content: string;
}

export default function LoadingComponent({
  inverted = true,
  content = 'Loading...',
}: LoadingComponentProps) {
  return (
    <Dimmer active={true} inverted={inverted}>
      <Loader content={content} />
    </Dimmer>
  );
}

// client-vue/src/app/components/Loading.vue
<template>
  <div class="ui segment">
    <div class="ui active dimmer">
      <div class="ui massive text loader">Loading</div>
    </div>
    <p></p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  props: {
    content: {
      type: String,
      required: true,
    },
    inverted: {
      type: Boolean,
      required: false,
    },
  },
});
</script>

<style scoped>
.ui.segment {
  width: 100%;
  height: 100vh;
}
</style>
