// client-app/src/app/layout/NavBar.tsx
import React from 'react';
import { Button, Container, Menu } from 'semantic-ui-react';

interface NavBarProps {
  openForm: (id?: string) => void;
}

export default function NavBar({ openForm }: NavBarProps) {
  return (
    <Menu inverted fixed='top'>
      <Container>
        <Menu.Item header>
          <img src='/assets/logo.png' alt='logo' style={{ marginRight: 10 }} />
          Reactivities
        </Menu.Item>
        <Menu.Item name='Activities' />
        <Menu.Item>
          <Button
            onClick={() => openForm()}
            positive
            content='Create Activity'
          />
        </Menu.Item>
      </Container>
    </Menu>
  );
}

// client-vue/src/app/components/NavBar.vue
<template>
  <div class="ui inverted top fixed menu">
    <div class="ui container">
      <router-link class="header item" :to="'/'">
        <img
          src="../../assets/logo.png"
          alt="logo"
          :style="{ marginRight: '10px' }"
        />
        Reactivities</router-link
      >
      <router-link to="/activities" class="item"> Activities</router-link>
      <div class="item">
        <router-link
          to="/createActivity"
          class="ui positive button"
          role="button"
        >
          Create Activity
        </router-link>
      </div>
    </div>
  </div>
</template>
