// client-vue/src/feature/activities/details/ActivityDetailedChat.vue
<template>
  <div
    class="ui teal inverted top attached center aligned segment"
    style="border: none"
  >
    <div class="ui header">Chat about this event</div>
  </div>
  <div class="ui attached segment">
    <div class="ui comments">
      <div class="comment">
        <div class="avatar">
          <img src="/assets/user.png" />
        </div>
        <div class="content">
          <router-link to="/" class="author"> Matt </router-link>
          <div class="metadata">
            <div>Today at 5:42PM</div>
          </div>
          <div class="text">How artistic!</div>
          <div class="actions"><a>Reply</a></div>
        </div>
      </div>
      <form class="ui reply form">
        <div class="field">
          <textarea rows="3"></textarea>
        </div>
        <button class="ui icon primary left labeled button">
          <i class="edit icon" />
          Add Reply
        </button>
      </form>
    </div>
  </div>
</template>

// client-react/src/features/activities/details/ActivityDetailedChat.tsx
import React, { useEffect } from 'react';
import { observer } from 'mobx-react-lite';
import { Formik, Form, Field, FieldProps } from 'formik';
import { Link } from 'react-router-dom';
import { Segment, Header, Comment, Loader } from 'semantic-ui-react';
import * as Yup from 'yup';
import { getProfileRoute } from '../../../app/constants/routes';
import { useStore } from '../../../app/stores/store';
import { formatDistanceToNow } from 'date-fns';

interface ActivityDetailedChatProps {
  activityId: string;
}

export default observer(function ActivityDetailedChat({
  activityId,
}: ActivityDetailedChatProps) {
  const { commentStore } = useStore();

  useEffect(() => {
    if (activityId) {
      commentStore.createHubConnection(activityId);
    }
    return () => {
      commentStore.clearComments();
    };
  }, [activityId, commentStore]);

  return (
    <>
      <Segment
        textAlign='center'
        attached='top'
        inverted
        color='teal'
        style={{ border: 'none' }}
      >
        <Header>Chat about this event</Header>
      </Segment>
      <Segment attached clearing>
        <Formik
          onSubmit={(values, { resetForm }) =>
            commentStore.addComment(values).then(() => resetForm())
          }
          initialValues={{ body: '' }}
          validationSchema={Yup.object({
            body: Yup.string().required(),
          })}
        >
          {({ isSubmitting, isValid, handleSubmit }) => (
            <Form className='ui form'>
              <Field name='body'>
                {(props: FieldProps) => (
                  <div style={{ position: 'relative' }}>
                    <Loader active={isSubmitting} />
                    <textarea
                      placeholder='Enter your comment (Enter to submit, SHIFT + enter fo new line)'
                      rows={2}
                      {...props.field}
                      onKeyPress={(e) => {
                        if (e.key === 'Enter' && e.shiftKey) {
                          return;
                        }
                        if (e.key === 'Enter' && !e.shiftKey) {
                          e.preventDefault();
                          if (isValid) {
                            handleSubmit();
                          }
                        }
                      }}
                    />
                  </div>
                )}
              </Field>
            </Form>
          )}
        </Formik>
        <Comment.Group>
          {commentStore.comments.map((comment) => (
            <Comment key={comment.id}>
              <Comment.Avatar src={comment.image || '/assets/user.png'} />
              <Comment.Content>
                <Comment.Author
                  as={Link}
                  to={getProfileRoute(comment.username)}
                >
                  {comment.displayName}
                </Comment.Author>
                <Comment.Metadata>
                  <div>{formatDistanceToNow(comment.createdAt)} ago</div>
                </Comment.Metadata>
                <Comment.Text style={{ whiteSpace: 'pre-wrap' }}>
                  {comment.body}
                </Comment.Text>
              </Comment.Content>
            </Comment>
          ))}
        </Comment.Group>
      </Segment>
    </>
  );
});
