// client-vue/src/feature/activities/details/ActivityDetailedInfo.vue
<template>
  <div class="ui segments">
    <div class="ui top attached segment">
      <div class="ui grid">
        <div class="one wide column">
          <i class="teal info large icon" />
        </div>
        <div class="fifteen wide column">
          <p>{{ activity.description }}</p>
        </div>
      </div>
    </div>
    <div class="ui attached segment">
      <div class="ui middle aligned grid">
        <div class="one wide column">
          <i class="calendar large icon teal" />
        </div>
        <div class="fifteen wide column">
          <span>{{ dateFormatted }}</span>
        </div>
      </div>
    </div>
    <div class="ui attached segment">
      <div class="ui middle aligned grid">
        <div class="one wide column">
          <i class="marker large teal icon" />
        </div>
        <div class="eleven wide column">
          <span> {{ activity.venue }}, {{ activity.city }} </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { format } from 'date-fns';
import { computed, defineComponent } from 'vue';
import { Activity } from '../../../app/models/activity';

export default defineComponent({
  props: {
    activity: {
      type: Object as () => Activity,
      required: true,
    },
  },
  setup(props) {
    const dateFormatted = computed<string>(() =>
      format(props.activity.date!, 'dd MMM yyyy h:mm aa')
    );

    return {
      dateFormatted,
    };
  },
});
</script>

// client-react/src/features/activities/details/ActivityDetailedInfo.tsx
import { observer } from 'mobx-react-lite';
import React from 'react';
import { Segment, Grid, Icon } from 'semantic-ui-react';
import { format } from 'date-fns';
import { Activity } from '../../../app/models/activity';

interface Props {
  activity: Activity;
}

export default observer(function ActivityDetailedInfo({ activity }: Props) {
  return (
    <Segment.Group>
      <Segment attached='top'>
        <Grid>
          <Grid.Column width={1}>
            <Icon size='large' color='teal' name='info' />
          </Grid.Column>
          <Grid.Column width={15}>
            <p>{activity.description}</p>
          </Grid.Column>
        </Grid>
      </Segment>
      <Segment attached>
        <Grid verticalAlign='middle'>
          <Grid.Column width={1}>
            <Icon name='calendar' size='large' color='teal' />
          </Grid.Column>
          <Grid.Column width={15}>
            <span>{format(activity.date!, 'dd MMM yyyy h:mm aa')}</span>
          </Grid.Column>
        </Grid>
      </Segment>
      <Segment attached>
        <Grid verticalAlign='middle'>
          <Grid.Column width={1}>
            <Icon name='marker' size='large' color='teal' />
          </Grid.Column>
          <Grid.Column width={11}>
            <span>
              {activity.venue}, {activity.city}
            </span>
          </Grid.Column>
        </Grid>
      </Segment>
    </Segment.Group>
  );
});
