// client-vue/src/feature/activities/details/ActivityDetailedHeader.vue
<template>
  <div class="ui segments">
    <div class="ui basic attached top segment" style="padding: 0">
      <img
        :src="`/assets/categoryImages/${activity.category}.jpg`"
        class="ui fluid image"
        style="filter: brightness(30%)"
      />
      <div
        class="ui basic segment"
        style="
          position: absolute;
          bottom: 5%;
          left: 5%;
          width: 100%;
          height: auto;
          color: white;
        "
      >
        <div class="ui items">
          <div class="item">
            <div class="content">
              <div class="ui huge header" style="color: white">
                {{ activity.title }}
              </div>
              <p>{{ dateFormatted }}</p>
              <p>Hosted by <strong>Bob</strong></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="ui clearing bottom attached segment">
      <button class="ui teal button">Join Activity</button>
      <button class="ui button">Cancel attendance</button>
      <router-link
        :to="{ name: MANAGE_ACTIVITY_PAGE_NAME, params: { id: activity.id } }"
        class="ui orange right floated button"
        >Manage Event</router-link
      >
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue';
import { format } from 'date-fns';
import { MANAGE_ACTIVITY_PAGE_NAME } from '../../../app/constants/routes';
import { Activity } from '../../../app/models/activity';
export default defineComponent({
  props: {
    activity: {
      type: Object as () => Activity,
      required: true,
    },
  },
  setup(props) {
    const dateFormatted = computed<string>(() =>
      format(props.activity.date!, 'dd MMM yyyy h:mm aa')
    );

    return {
      dateFormatted,
      MANAGE_ACTIVITY_PAGE_NAME,
    };
  },
});
</script>

// client-react/src/features/activities/details/ActivityDetailedHeader.tsx
import { observer } from 'mobx-react-lite';
import React from 'react';
import { Link } from 'react-router-dom';
import { Button, Header, Item, Segment, Image, Label } from 'semantic-ui-react';
import { format } from 'date-fns';
import { getManageActivityRoute } from '../../../app/constants/routes';
import { Activity } from '../../../app/models/activity';
import { useStore } from '../../../app/stores/store';

const activityImageStyle = {
  filter: 'brightness(30%)',
};

const activityImageTextStyle = {
  position: 'absolute',
  bottom: '5%',
  left: '5%',
  width: '100%',
  height: 'auto',
  color: 'white',
};

interface Props {
  activity: Activity;
}

export default observer(function ActivityDetailedHeader({ activity }: Props) {
  const {
    activityStore: { updateAttendance, isLoading, cancelActivityToggle },
  } = useStore();
  return (
    <Segment.Group>
      <Segment basic attached='top' style={{ padding: '0' }}>
        {activity.isCancelled && (
          <Label
            style={{ position: 'absolute', zIndex: 1000, left: -14, top: 20 }}
            ribbon
            color='red'
            content='Cancelled'
          />
        )}
        <Image
          src={`/assets/categoryImages/${activity.category}.jpg`}
          fluid
          style={activityImageStyle}
        />
        <Segment style={activityImageTextStyle} basic>
          <Item.Group>
            <Item>
              <Item.Content>
                <Header
                  size='huge'
                  content={activity.title}
                  style={{ color: 'white' }}
                />
                <p>{format(activity.date!, 'dd MMM yyyy h:mm aa')}</p>
                <p>
                  Hosted by{' '}
                  <strong>
                    <Link to={`/profiles/${activity.id}`}>
                      {activity.host?.displayName}
                    </Link>
                  </strong>
                </p>
              </Item.Content>
            </Item>
          </Item.Group>
        </Segment>
      </Segment>
      <Segment clearing attached='bottom'>
        {activity.isHost ? (
          <>
            <Button
              color={activity.isCancelled ? 'green' : 'red'}
              floated='left'
              basic
              content={
                activity.isCancelled
                  ? 'Re-activate Activity'
                  : 'Cancel Activity'
              }
              onClick={cancelActivityToggle}
              loading={isLoading}
            />
            <Button
              disabled={activity.isCancelled}
              as={Link}
              to={getManageActivityRoute(activity.id)}
              color='orange'
              floated='right'
            >
              Manage Event
            </Button>
          </>
        ) : activity.isGoing ? (
          <Button loading={isLoading} onClick={updateAttendance}>
            Cancel attendance
          </Button>
        ) : (
          <Button
            disabled={activity.isCancelled}
            loading={isLoading}
            onClick={updateAttendance}
            color='teal'
          >
            Join Activity
          </Button>
        )}
      </Segment>
    </Segment.Group>
  );
});
