// client-vue/src/feature/activities/dashboard/ActivityFilters.vue
<template>
  <div class="ui large vertical menu">
    <div class="ui teal attached header">
      <i class="filter icon" />
      <div class="content">Filters</div>
    </div>
    <div class="item">All Activities</div>
    <div class="item">I'm going</div>
    <div class="item">I'm hosting</div>
  </div>
  <div class="ui header"></div>
  <Calendar />
</template>

<script>
import { defineComponent } from 'vue';
import { Calendar } from 'v-calendar';

export default defineComponent({
  components: {
    Calendar,
  },
});
</script>

// client-react/src/features/activities/dashboard/ActivityFilters.tsx
import React from 'react';
import { observer } from 'mobx-react-lite';
import { Header, Menu } from 'semantic-ui-react';
import Calendar from 'react-calendar';
import { useStore } from '../../../app/stores/store';

export default observer(function ActivityFilters() {
  const {
    activityStore: { predicate, setPredicate },
  } = useStore();

  return (
    <>
      <Menu vertical size='large' style={{ width: '100%', marginTop: 25 }}>
        <Header icon='filter' attached color='teal' content='Filters' />
        <Menu.Item
          content='All Activities'
          active={predicate.has('all')}
          onClick={() => setPredicate('all', true)}
        />
        <Menu.Item
          content="I'm going"
          active={predicate.has('isGoing')}
          onClick={() => setPredicate('isGoing', true)}
        />
        <Menu.Item
          content="I'm hosting"
          active={predicate.has('isHost')}
          onClick={() => setPredicate('isHost', true)}
        />
      </Menu>
      <Header />
      <Calendar
        onChange={(date) => setPredicate('startDate', date as Date)}
        value={(predicate.get('startDate') as Date) || new Date()}
      />
    </>
  );
});
