// client-vue/src/feature/activities/dashboard/ActivityListItem.vue
<template>
  <div class="ui segments">
    <div class="ui segement host">
      <div class="ui items">
        <div class="item">
          <div class="ui tiny circular image">
            <img src="/assets/user.png" />
          </div>
          <div class="content">
            <router-link
              class="header"
              :to="{
                name: ACTIVITY_DETAILS_PAGE_NAME,
                params: { id: activity.id },
              }"
            >
              {{ activity.title }}
            </router-link>
            <div class="description">Hosted by Bob</div>
          </div>
        </div>
      </div>
    </div>
    <div class="ui segment">
      <span>
        <i class="clock icon" />
        {{ dateFormatted }}
        <i class="marker icon" />
        {{ activity.venue }}
      </span>
    </div>
    <div class="ui secondary segment">Attendees go here</div>
    <div class="ui clearing segment">
      <span>{{ activity.description }}</span>
      <router-link
        :to="{ name: ACTIVITY_DETAILS_PAGE_NAME, params: { id: activity.id } }"
        class="ui teal right floated button"
        role="button"
      >
        View
      </router-link>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue';
import { format } from 'date-fns';
import { ACTIVITY_DETAILS_PAGE_NAME } from '../../../app/constants/routes';
import { Activity } from '../../../app/models/activity';
import { useStore } from '../../../app/store';

export default defineComponent({
  props: {
    activity: {
      type: Object as () => Activity,
      required: true,
    },
  },
  setup(props) {
    const store = useStore();

    const isLoading = computed<boolean>(() => store.getters.getIsLoading);
    const dateFormatted = computed<string>(() =>
      format(props.activity.date!, 'dd MMM yyyy h:mm aa')
    );

    return {
      isLoading,
      dateFormatted,
      ACTIVITY_DETAILS_PAGE_NAME,
    };
  },
});
</script>

<style scoped>
.host {
  padding: 15px;
  background-color: #ffffff;
}
</style>

// client-react/src/features/activities/dashboard/ActivityListItem.tsx
import React from 'react';
import { Item, Button, Segment, Icon, Label } from 'semantic-ui-react';
import { Link } from 'react-router-dom';
import { format } from 'date-fns';
import { getActivityDetailsRoute } from '../../../app/constants/routes';
import { Activity } from '../../../app/models/activity';
import ActivityListItemAttendee from './ActivityListItemAttendee';

interface ActivityListItemProps {
  activity: Activity;
}

export default function ActivityListItem({
  activity,
}: ActivityListItemProps): JSX.Element {
  return (
    <Segment.Group>
      <Segment>
        {activity.isCancelled && (
          <Label
            attached='top'
            color='red'
            content='Cancelled'
            style={{ textAlign: 'center' }}
          />
        )}
        <Item.Group>
          <Item>
            <Item.Image
              style={{ marginBottom: 3 }}
              size='tiny'
              circular
              src='/assets/user.png'
            />
            <Item.Content>
              <Item.Header as={Link} to={getActivityDetailsRoute(activity.id)}>
                {activity.title}
              </Item.Header>
              <Item.Description>
                Hosted by {activity.host?.displayName}
              </Item.Description>
              {activity.isHost && (
                <Item.Description>
                  <Label basic color='orange'>
                    You are hosting this activity
                  </Label>
                </Item.Description>
              )}
              {activity.isGoing && !activity.isHost && (
                <Item.Description>
                  <Label basic color='green'>
                    You are going to this activity
                  </Label>
                </Item.Description>
              )}
            </Item.Content>
          </Item>
        </Item.Group>
      </Segment>
      <Segment>
        <span>
          <Icon name='clock' /> {format(activity.date!, 'dd MMM yyyy h:mm aa')}
          <Icon name='marker' /> {activity.venue}
        </span>
      </Segment>
      <Segment secondary>
        <ActivityListItemAttendee attendees={activity.attendees!} />
      </Segment>
      <Segment clearing>
        <span>{activity.description}</span>
        <Button
          as={Link}
          to={getActivityDetailsRoute(activity.id)}
          color='teal'
          floated='right'
          content='View'
        />
      </Segment>
    </Segment.Group>
  );
}
