// client-vue/src/feature/activities/dashboard/ActivityDashboard.vue
<template>
  <div v-if="!isLoadingInitial" class="ui grid">
    <div class="ten wide column">
      <ActivityList />
    </div>
    <div class="six wide column">
      <ActivityFilters/>
    </div>
  </div>
  <Loading v-else content="Loading app" />
</template>

<script lang="ts">
import { computed, defineComponent, watch } from 'vue';
import ActivityList from './ActivityList.vue';
import ActivityFilters from './ActivityFilters.vue';
import Loading from '../../../app/components/Loading.vue';
import { useStore } from '../../../app/store';
import { AllActionTypes } from '../../../app/store/action-types';

export default defineComponent({
  components: {
    ActivityList,
    ActivityFilters,
    Loading,
  },
  setup() {
    const store = useStore();
    const isLoadingInitial = computed<boolean>(
      () => store.getters.getIsLoadingInitial
    );

    watch(
      store.getters.getGroupedActivities,
      () => {
        store.dispatch(AllActionTypes.LOAD_ACTIVITIES);
      },
      {
        immediate: true,
      }
    );

    return {
      isLoadingInitial,
    };
  },
});
</script>

// client-react/src/features/activities/dashboard/ActivityDashboard.tsx
import { observer } from 'mobx-react-lite';
import React, { useEffect } from 'react';
import { Grid } from 'semantic-ui-react';
import LoadingComponent from '../../../app/layout/LoadingComponent';
import { useStore } from '../../../app/stores/store';
import ActivityFilters from './ActivityFilters';
import ActivityList from './ActivityList';

export default observer(function ActivityDashboard() {
  const { activityStore } = useStore();
  const { loadActivities, activityRegistry } = activityStore;

  useEffect(() => {
    if (activityRegistry.size <= 1) {
      loadActivities();
    }
  }, [activityRegistry.size, loadActivities]);

  return activityStore.isLoadingInitial ? (
    <LoadingComponent content='Loading app' />
  ) : (
    <Grid>
      <Grid.Column width='10'>
        <ActivityList />
      </Grid.Column>
      <Grid.Column width='6'>
        <ActivityFilters />
      </Grid.Column>
    </Grid>
  );
});
