// client-vue/src/app/components/Loading.vue
<template>
  <div class="ui segment">
    <div class="ui active dimmer">
      <div class="ui massive text loader">Loading</div>
    </div>
    <p></p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  props: {
    content: {
      type: String,
      required: true,
    },
    inverted: {
      type: Boolean,
      required: false,
    },
  },
});
</script>

<style scoped>
.ui.segment {
  width: 100%;
  height: 100vh;
}
</style>

// client-angular/src/app/core/loading/loading.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-loading',
  templateUrl: './loading.component.html',
  styleUrls: ['./loading.component.css']
})
export class LoadingComponent implements OnInit {

  @Input() content: string;
  @Input() inverted: boolean;
  
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="ui segment">
  <div class="ui active dimmer">
    <div class="ui massive text loader">Loading</div>
  </div>
  <p></p>
</div>
