// client-react/src/features/activities/details/ActivityDetailedSidebar.tsx
import React from 'react';
import { Segment, List, Label, Item, Image } from 'semantic-ui-react';
import { Link } from 'react-router-dom';
import { observer } from 'mobx-react-lite';
import { Activity } from '../../../app/models/activity';

interface ActivityDetailedSidebarProps {
  activity: Activity;
}

export default observer(function ActivityDetailedSidebar({
  activity: { attendees, host },
}: ActivityDetailedSidebarProps) {
  return !attendees ? null : (
    <>
      <Segment
        textAlign='center'
        style={{ border: 'none' }}
        attached='top'
        secondary
        inverted
        color='teal'
      >
        {attendees.length} {attendees.length === 1 ? 'Person' : 'People'} going
      </Segment>
      <Segment attached>
        <List relaxed divided>
          {attendees.map((attendee) => (
            <Item style={{ position: 'relative' }} key={attendee.username}>
              {attendee.username === host?.username && (
                <Label
                  style={{ position: 'absolute' }}
                  color='orange'
                  ribbon='right'
                >
                  Host
                </Label>
              )}
              <Image size='tiny' src={attendee.image || '/assets/user.png'} />
              <Item.Content verticalAlign='middle'>
                <Item.Header as='h3'>
                  <Link to={`/profiles/${attendee.username}`}>
                    {attendee.displayName}
                  </Link>
                </Item.Header>
                <Item.Extra style={{ color: 'orange' }}>Following</Item.Extra>
              </Item.Content>
            </Item>
          ))}
        </List>
      </Segment>
    </>
  );
});

// client-vue/src/feature/activities/details/ActivityDetailedSidebar.vue
<template>
  <div
    class="ui teal inverted secondary top attached center aligned segment"
    style="border: none"
  >
    3 People Going
  </div>
  <div class="ui attached segment">
    <div class="ui divided relaxed list" role="list">
      <div class="item" style="position: relative">
        <div class="ui orange right ribbon label" style="position: absolute">
          Host
        </div>
        <img src="/assets/user.png" class="ui tiny image" />
        <div class="middle aligned content">
          <h3 class="header">
            <router-link to="#">Bob</router-link>
          </h3>
          <div class="extra" style="color: orange">Following</div>
        </div>
      </div>
      <div class="item" style="position: relative">
        <img src="/assets/user.png" class="ui tiny image" />
        <div class="middle aligned content">
          <h3 class="header">
            <router-link to="#">Tom</router-link>
          </h3>
          <div class="extra" style="color: orange">Following</div>
        </div>
      </div>
    </div>
  </div>
</template>
