// client-app/src/features/activities/details/ActivityDetails.tsx
import React from 'react';
import { Card, Image, Button } from 'semantic-ui-react';
import { Activity } from '../../../app/models/activity';

interface ActivityDetailsProps {
  activity: Activity;
  cancelSelectActivity: () => void;
  openForm: (id?: string) => void;
}

export default function ActivityDetails({
  activity,
  cancelSelectActivity,
  openForm,
}: ActivityDetailsProps) {
  return (
    <Card fluid>
      <Image src={`/assets/categoryImages/${activity.category}.jpg`} />
      <Card.Content>
        <Card.Header>{activity.title}</Card.Header>
        <Card.Meta>
          <span className='date'>{activity.date}</span>
        </Card.Meta>
        <Card.Description>{activity.description}</Card.Description>
      </Card.Content>
      <Card.Content extra>
        <Button.Group widths='2'>
          <Button
            onClick={() => openForm(activity.id)}
            basic
            color='blue'
            content='Edit'
          />
          <Button
            onClick={cancelSelectActivity}
            basic
            color='grey'
            content='Cancel'
          />
        </Button.Group>
      </Card.Content>
    </Card>
  );
}

// client-vue/src/feature/activities/details/ActivityDetails.vue
<template>
  <div v-if="!(isLoadingInitial || !activity)" class="ui fluid card">
    <img :src="`../assets/categoryImages/${activity.category}.jpg`" />
    <div class="content">
      <div class="header">
        {{ activity.title }}
      </div>
      <div class="meta">
        <span class="date">{{ activity.date }}</span>
      </div>
      <div class="description">
        {{ activity.description }}
      </div>
    </div>
    <div class="extra content">
      <div class="ui two buttons">
        <router-link
          :to="`/manage/${activity.id}`"
          class="ui blue basic button"
        >
          Edit
        </router-link>
        <button class="ui grey basic button">Cancel</button>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { useStore } from "../../../app/store";
import { defineComponent, computed, onMounted } from "vue";
import { AllActionTypes } from "../../../app/store/action-types";
import { Activity } from "../../../app/models/activity";
import { useRoute } from 'vue-router';

export default defineComponent({
  setup() {
    const store = useStore();
    const route = useRoute();

    onMounted(() => {
      store.dispatch(
        AllActionTypes.LOAD_ACTIVITY,
        route.params.id.toString()
      );
    });

    const activity = computed<Activity | undefined>(() => {
      return store.getters.getSelectedActivity;
    });
    const isLoadingInitial = computed<boolean>(
      () => store.getters.getIsLoadingInitial
    );

    return {
      activity,
      isLoadingInitial,
    };
  },
});
</script>
